services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=storage_db'
      - 'POSTGRES_PASSWORD=bestUser'
      - 'POSTGRES_USER=bestUser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
