spring.application.name=storage

spring.datasource.url=jdbc:postgresql://localhost:5432/storage_db
spring.datasource.username=bestUser
spring.datasource.password=bestUser

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.session.store-type=redis

minio.url=http://localhost:9010
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=user-files
